### ISSUE TITLE
es 插件 java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by sure0000** [apache/incubator-seatunnel#556]
**Waterdrop Version(Waterdrop版本)**

wd-v2-baseline

**Flink or Spark Version(Flink 或者 Spark 版本)**

flink-1.9.2

**Java or Scala Version(Java或者Scala版本)**

jdk 1.8.0_111

**yarn 版本**

社区版本：2.7.7

**Waterdrop Config(Waterdrop配置文件)**

```
env {
  execution.parallelism = 1
}

source {
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}

transform {
    sql {
      sql = "select name,age from fake"
    }
}

sink {
  elasticsearch {
                hosts = ["data153:9200"]
                index = "waterdrop_xtc_test"
        }
     #ConsoleSink{}
}

```

**Running Command(启动命令)**

`bin/start-waterdrop-flink.sh --config config/flink.streaming.conf.template -m yarn-cluster -yqu 28a6b34032954fc4b6fce57176a16abd -ynm test01`

**Error Exception**
```
org.apache.flink.client.program.ProgramInvocationException: Job failed. (JobID: e3fa30c83e3d64ea78a754e13db78100)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:262)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:338)
	at org.apache.flink.streaming.api.environment.StreamContextEnvironment.execute(StreamContextEnvironment.java:60)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1507)
	at io.github.interestinglab.waterdrop.flink.stream.FlinkStreamExecution.start(FlinkStreamExecution.java:58)
	at io.github.interestinglab.waterdrop.Waterdrop.entryPoint(Waterdrop.java:91)
	at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:50)
	at io.github.interestinglab.waterdrop.WaterdropFlink.main(WaterdropFlink.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:604)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:466)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1008)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1081)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1081)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:147)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:259)
	... 24 more
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:53)
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:57)
	at org.apache.http.impl.nio.codecs.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:47)
	at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<init>(ManagedNHttpClientConnectionFactory.java:75)
	at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<init>(ManagedNHttpClientConnectionFactory.java:83)
	at org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionFactory.<clinit>(ManagedNHttpClientConnectionFactory.java:64)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingNHttpClientConnectionManager.java:553)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:163)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:147)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:119)
	at org.apache.http.impl.nio.client.HttpAsyncClientBuilder.build(HttpAsyncClientBuilder.java:668)
	at org.elasticsearch.client.RestClientBuilder$2.run(RestClientBuilder.java:216)
	at org.elasticsearch.client.RestClientBuilder$2.run(RestClientBuilder.java:213)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:213)
	at org.elasticsearch.client.RestClientBuilder.access$000(RestClientBuilder.java:42)
	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:186)
	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:183)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:183)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:204)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:196)
	at org.apache.flink.streaming.connectors.elasticsearch6.Elasticsearch6ApiCallBridge.createClient(Elasticsearch6ApiCallBridge.java:75)
	at org.apache.flink.streaming.connectors.elasticsearch6.Elasticsearch6ApiCallBridge.createClient(Elasticsearch6ApiCallBridge.java:47)
	at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.open(ElasticsearchSinkBase.java:299)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:552)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:416)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:745)

```

**Screenshots**

**Comment by RickyHuo** [comment]
@sure0000 请提供一下Yarn的版本 是CDH的吗？

**Comment by sure0000** [comment]
@RickyHuo 社区版本：2.7.7

**Comment by RickyHuo** [comment]
初步看和 https://github.com/InterestingLab/waterdrop/issues/267#issuecomment-481063042 类似的 httpclient 版本问题，看下集群 httpclient 的版本

**Comment by sure0000** [comment]
是 yarn 集群还是 flink ? flink 是 1.9.2 版本，yarn http 包 httpclient-4.2.5.jar。 @RickyHuo

**Comment by RickyHuo** [comment]
可以尝试升级Yarn集群里的httpclient以解决问题 @sure0000

**Comment by sure0000** [comment]
@RickyHuo  使用 2.0 的 alpha 版本没有这个问题
