### ISSUE TITLE
jar包冲突了，需要重新打包waterdrop-core-2.0.4-2.11.8.jar么？

### ISSUE THREAD

**Issue by ruizhang81** [apache/incubator-seatunnel#610]
**Waterdrop Version(2.0.4-2.11.8.)**

**Flink or Spark Version(SPARK2-2.2.0)**

**Java or Scala Version(Java1.8)**

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
env {
  spark.app.name = "hive-ck"
  spark.executor.instances = 8
  spark.executor.cores = 2
  spark.executor.memory = "2g"
}

source {
  Fake {
    result_table_name = "phone_idcard"
  }
}

transform {

}

sink {
  clickhouse {
    host = "172.17.6.48:8123"
    database = "mingzhi_808"
    clickhouse.socket_timeout=600000
     table = "phone_idcard"
    username = "test"
    password = "123"
    bulk_size = 50000
    retry = 3
  }
}
```

**Running Command(启动命令)**

./bin/start-waterdrop-spark.sh --master yarn --deploy-mode client -c ./config/test.conf

**Error Exception**

Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.commons.compiler.Location.<init>(Ljava/lang/String;III)V
        at org.codehaus.janino.Scanner.location(Scanner.java:233)
        at org.codehaus.janino.Parser.location(Parser.java:3135)
        at org.codehaus.janino.Parser.parseImportDeclarationBody(Parser.java:275)
        at org.codehaus.janino.ClassBodyEvaluator.makeCompilationUnit(ClassBodyEvaluator.java:258)

**Screenshots**
![11](https://user-images.githubusercontent.com/3723124/107137551-913a2200-6948-11eb-8f85-531d15edf327.jpg)

**Comment by RickyHuo** [comment]
@ruizhang81  请根据模版提供详细信息 参考https://github.com/InterestingLab/waterdrop/issues/new?assignees=&labels=&template=----------issue.md&title=

**Comment by ruizhang81** [comment]
修改了

**Comment by RickyHuo** [comment]
@ruizhang81 试一下1.5.1 的版本

**Comment by ruizhang81** [comment]
现在是另一个错了
21/02/07 15:33:47 INFO batch.Clickhouse: insert into phone_idcard (`idcard`,`phone`,`score`) values (?,?,?)
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hive.common.util.HiveStringUtils.joinIgnoringEmpty([Ljava/lang/String;C)Ljava/lang/String;
        at org.apache.hadoop.hive.serde2.ColumnProjectionUtils.appendReadColumns(ColumnProjectionUtils.java:99)
        at org.apache.spark.sql.hive.HiveShim$.appendReadColumns(HiveShim.scala:76)
        at org.apache.spark.sql.hive.execution.HiveTableScanExec.addColumnMetadataToConf(HiveTableScanExec.scala:119)
