### ISSUE TITLE
[Bug] [start-seatunnel-spark.sh] The seatunnel conf file is abnormal, and the exit status is correct

### ISSUE THREAD

**Issue by KinoMin** [apache/incubator-seatunnel#718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

我司通过azkaban调度运行中间Java程序动态生成seatunnel conf文件，在start-seatunnel-spark.sh 的 123 行有进行conf文件校验，验证不通过会 exit -1，这里并没有中断这个shell的后续执行，导致spark-submit 提交失败，在azkaban中显示Success而不是Failed。

### SeaTunnel Version

master

### SeaTunnel Config

```conf
env {
	# spark.app.name = "Waterdrop"
}
source {
  jdbc {
    driver = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://XXXX:xxx/xxxx?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    # 此处可以替换成任意导致
    table = "(drop table if exists wrk_dwd_dim_store_item_labels;\n\nCREATE TABLE `wrk_dwd_dim_store_item_labels` (\n  `tenant_id` int(11) NULL COMMENT "",\n  `store_id` varchar(20) NULL COMMENT "",\n  `item_id` varchar(20) NULL COMMENT "",\n  `item_name` varchar(255) NULL COMMENT "",\n  `sales_rank` int(11) NULL COMMENT "",\n  `item_class` varchar(20) NULL COMMENT "",\n  `is_normal_item` int(11) NULL COMMENT "",\n  `is_new_item` int(11) NULL COMMENT "",\n  `is_fresh_item` int(11) NULL COMMENT "",\n  `is_manage_jointly_item` int(11) NULL COMMENT "",\n  `first_sale_time` date NULL COMMENT "",\n  `last_sale_time` date NULL COMMENT "",\n  `etl_time` datetime NULL COMMENT ""\n)\nDISTRIBUTED BY HASH(`tenant_id`, `store_id`) BUCKETS 4;) AS t"
    result_table_name = "t"
    user = "xxxx"
    password = "xxxx"
}


}
transform {
  
}
sink {
  console {
	source_table_name = t
}

}
```

### Running Command

```shell
/app/idas-prod/idas_waterdrop/prd/bin/start-waterdrop-spark.sh --master y --deploy-mode client a--config /app/idas-prod/idas_cmdexecutortool/prd/conf/sql/dwd_dim_store_item_labelsaaa_application_2354.conf
```

### Error Exception

```log
Exception in thread "main" io.github.interestinglab.waterdrop.config.ConfigException$Parse: /app/waterdrop/prd/conf/sql/dwd_dim_store_item_labelsaaa_application_2352.conf: 15: Expecting close brace } or a comma, got 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) (if you intended 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:207)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:203)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:534)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:253)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:464)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:253)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:464)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:654)
		at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:20)
		at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:264)
		at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:252)
		at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:184)
		at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:178)
		at io.github.interestinglab.waterdrop.config.impl.Parseable.parse(Parseable.java:303)
		at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:689)
		at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:703)
		at io.github.interestinglab.waterdrop.config.ExposeSparkConf.main(ExposeSparkConf.java:9)
	[INFO] spark conf: [ERROR] config file does not exists or cannot be parsed due to invalid format
	21/11/26 15:45:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[TRACEID:] 2021-11-26 15:45:48.753  INFO 545 --- [           main] c.j.d.c.s.s.worker.task.TaskManager      : process has exited, execute path:/app/waterdrop/prd/conf, processId:1125 ,exitStatusCode:0
[TRACEID:] 2021-11-26 15:45:48.753  INFO 545 --- [_item_labelsaaa] c.j.d.c.s.s.worker.task.TaskManager      :  -> Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
	21/11/26 15:45:48 WARN DependencyUtils: Local jar /app/idas-prod/idas_cmdexecutortool/prd/conf/[ERROR] does not exist, skipping.
	Error: Unknown argument 'config'
	Error: Unknown argument 'file'
	Error: Unknown argument 'does'
	Error: Unknown argument 'not'
	Error: Unknown argument 'exists'
	Error: Unknown argument 'or'
	Error: Unknown argument 'cannot'
	Error: Unknown argument 'be'
	Error: Unknown argument 'parsed'
	Error: Unknown argument 'due'
	Error: Unknown argument 'to'
	Error: Unknown argument 'invalid'
	Error: Unknown argument 'format'
	Error: Unknown argument '/app/idas-prod/idas_waterdrop/prd/lib/waterdrop-core-2.0.4-2.11.8.jar'
	Waterdrop 2.0.0
	Usage: start-waterdrop-spark.sh [options]
	
	  -c, --config <value>     config file
	  -t, --check              check config
	  -e, --deploy-mode <value>
	                           spark deploy mode
	  -m, --master <value>     spark master
	  -i, --variable <value>   variable substitution, such as -i city=beijing, or -i date=20190318
	21/11/26 15:45:48 INFO ShutdownHookManager: Shutdown hook called
	21/11/26 15:45:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-d0050b95-fcf9-457b-a16f-7a50e60784c0
```

### Flink or Spark Version

Apache Spark2.4.8

### Java or Scala Version

openjdk version "1.8.0_312"

### Screenshots

![image](https://user-images.githubusercontent.com/56473938/143550270-f8d85b87-5801-47f0-a9b5-54f32800c4be.png)
![image](https://user-images.githubusercontent.com/56473938/143550173-ae09092b-c422-4ad1-8272-30e551d3e1b7.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KinoMin** [comment]
![image](https://user-images.githubusercontent.com/56473938/143554453-cc955e25-3765-4423-b9e2-a50261ad0501.png)
