### ISSUE TITLE
[Bug] [seatunnel-dist] dev branch dist commit job failed

### ISSUE THREAD

**Issue by chaozwn** [apache/incubator-seatunnel#989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

exec /Users/artefact/Downloads/flink-1.9.3/bin/flink run -c org.apache.seatunnel.SeatunnelFlink /Users/artefact/Documents/seatunnel-dist-2.0.5-SNAPSHOT-2.11.8/lib/seatunnel-core-flink.jar --config ./config/flink.streaming.conf.template  
above is running cmd，but seatunnel-core-flink.jar not contains seatunnel-core-base.jar

### SeaTunnel Version

2.X

### SeaTunnel Config

```conf
flink.streaming.conf.template
```

### Running Command

```shell
sh -x bin/start-seatunnel-flink.sh --config ./config/flink.streaming.conf.template
```

### Error Exception

```log
java.lang.NoClassDefFoundError: org/apache/seatunnel/config/command/CommandLineUtils
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:604)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:466)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1008)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1081)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1081)
Caused by: java.lang.ClassNotFoundException: org.apache.seatunnel.config.command.CommandLineUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.util.ChildFirstClassLoader.loadClass(ChildFirstClassLoader.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

### Flink or Spark Version

FLINK1.9

### Java or Scala Version

java8

### Screenshots

![image](https://user-images.githubusercontent.com/51357674/148723968-8f7ab659-d186-4f6c-92cd-b79db76ac13c.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leo65535** [comment]
Nice catch, do you find anything?

**Comment by leo65535** [comment]
Hi @chaozwn, https://github.com/apache/incubator-seatunnel/pull/1002 can fix this issue.
